import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/user/layout/Navbar";
import Footer from "@/components/user/layout/Footer";
import { Toaster } from "react-hot-toast";
import AOSProvider from "@/components/ui/AOSProvider";

import { Cormorant_Garamond } from "next/font/google";
import Providers from "./providers";

const cormorant = Cormorant_Garamond({
  subsets: ["latin"],
  weight: ["300", "400"],
  variable: "--font-serif",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`bg-eco-black text-text-primary ${cormorant.variable} antialiased`}
      >
        <Providers>
          <AOSProvider />
          <Navbar />
          {children}
          <Footer />
          <Toaster position="top-right" />
        </Providers>
      </body>
    </html>
  );
}
